script:
- npm install
- npm run test
language: node_js
node_js:
- 8.1
branches:
  only:
  - master
  - develop
notifications:
  slack:
    secure: Gq5KYqpeg02LiwmuKtLiu4S5ID4UMr8YJ5S/PX+3stwfz3VzSkT/UYzdaAI5uUqUG1z1TuM4O33iNC3HdoTserL6CE5Odsks0rze63ECNjbpqr9crwz0PnxzwVZElPN7n7092tvg0uaCIOqDLvT0yV19uoCoiWsmAZDHQkVQlQWK7AL3H6FPCOc09VbrmL4zN3McdMD5VsNhBZops0Pq1i3yDw5ybPKPJ//ssLeCOj+MKbE1I8dKmmcSFm0iq74hSEqbr1VYslQsOC8QW/Z4UnEAcY22wcqVHgEHtuDddQ9BUtQgVIyAP5E2LWof+SP5xvp2wpm1I0sYJNb47HgQ03Kq84f5g8yBQsKF6OSrQIU/wjmC9DYKAIhT5YQfjcHtMhqbkIm10iIdilkEEYwiTbILelXHKsoArVecTqZAGtUa5sCCugtsWXpQnB/5zMMoTeVRiNJa4pLXmCqj8TUvG1LvNVDhqk9caIBOVu+PGieAyJdkgVjK8Nm+AA6Gk853NY3qggwyVysj8Ht+Svzp9plNNKPdP2sFW5fdX3cG08iOGDnkCrK26XKO5uOTYK+lVT0vNRg7xKXpJudXcZNfkqeGvLQ6BS3QwOWkxjun1k8oMr4TZf3dPLZNyI5TuEFIomG79vUUdaBpgy7WmKhS4eRF3M+mkSrBIN36B2go2uU=
